// File generated by FlutterFire CLI.
// DO NOT EDIT - This file is auto-generated by the FlutterFire CLI.
// You will need to run `flutterfire configure` to set up Firebase properly

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    // Fallback for unsupported platforms (macOS, Linux, Web)
    return android; // Use Android config as fallback
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPniP116Vp422R0keYjiOc8h2y8qxPrtU',
    appId: '1:850925345028:web:a1234567890abcdef',
    messagingSenderId: '850925345028',
    projectId: 'musicplayerapp-flutter',
    authDomain: 'musicplayerapp-flutter.firebaseapp.com',
    storageBucket: 'musicplayerapp-flutter.firebasestorage.app',
  );

  // Android configuration filled from `android/app/google-services.json`.
  // If you later regenerate platform files via the Firebase Console,
  // run `flutterfire configure` to update this file automatically.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPniP116Vp422R0keYjiOc8h2y8qxPrtU',
    appId: '1:850925345028:android:966cb15b9025391eec5851',
    messagingSenderId: '850925345028',
    projectId: 'musicplayerapp-flutter',
    databaseURL: 'https://musicplayerapp-flutter.firebaseio.com',
    storageBucket: 'musicplayerapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPniP116Vp422R0keYjiOc8h2y8qxPrtU',
    appId: '1:850925345028:ios:abcd1234efgh5678',
    messagingSenderId: '850925345028',
    projectId: 'musicplayerapp-flutter',
    databaseURL: 'https://musicplayerapp-flutter.firebaseio.com',
    storageBucket: 'musicplayerapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.music_player',
  );
}
